# Generated by Django 4.1.7 on 2023-03-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_avatars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatars',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
